# Docker Compose Override for Development
# This file extends compose.yaml with development-specific settings
# It's automatically loaded by docker compose when present

services:
  web:
    # Enable debugging and development features
    environment:
      - DEBUG=true
      - NUXT_DEBUG=true
      - NODE_OPTIONS=--inspect=0.0.0.0:9229  # Enable Node.js debugging
    ports:
      - "9229:9229"  # Expose Node.js debugger port
    # Override development command for debugging
    # Uncomment the line below to enable debugging
    # command: ["node", "--inspect=0.0.0.0:9229", "node_modules/.bin/nuxt", "dev"]
    
    # Development-specific volume mounts
    volumes:
      # Mount source code for hot reload
      - .:/app:cached
      # Exclude node_modules from being overwritten
      - /app/node_modules
      # Mount additional development directories
      - ./.nuxt:/app/.nuxt
      - ./static:/app/static
      - ./assets:/app/assets
      - ./components:/app/components
      - ./layouts:/app/layouts
      - ./middleware:/app/middleware
      - ./pages:/app/pages
      - ./plugins:/app/plugins
      - ./server:/app/server
      - ./store:/app/store
    
    # Development-specific labels for easier identification
    labels:
      - "dev.webchessclock.service=web"
      - "dev.webchessclock.environment=development"

  redis:
    # Development-specific Redis configuration
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=everysec
    
    # Development-specific labels
    labels:
      - "dev.webchessclock.service=redis"
      - "dev.webchessclock.environment=development"
    
    # Enable Redis CLI access for debugging
    command: >
      redis-server 
      --appendonly yes 
      --appendfsync everysec 
      --save 60 1 
      --loglevel notice 
      --maxmemory 256mb 
      --maxmemory-policy allkeys-lru